#!/usr/bin/env bash
# panel config. Powerline style.

panel_fifo="/tmp/xmonad_lemonbar_${USER}"
geometry="x14"
# font="-xos4-terminesspowerline-medium-r-normal--12-120-72-72-c-60-iso10646-1"
# iconfont="-xos4-terminusicons2mono-medium-r-normal--12-120-72-72-m-60-iso8859-1"
font="Inconsolata Nerd Font Mono-9:style=Regular"
# font="Droid Sans Mono Nerd Font-9:style=Regular"
iconfont="Inconsolata Nerd Font Mono-9:style=Regular"
# iconfont="Droid Sans Mono Nerd Font-8"
res_w=$(xrandr | grep "current" | awk '{print $8a}')
snd_cha=$(amixer get Master | grep "Playback channels:" | awk '{if ($4 == "") {printf "%s: Playback", $3} else {printf "%s %s: Playback", $3, $4}}')

# Alarm settings
cpu_alert=75                        # % cpu use
net_alert=5                         # K net use

# update setting, in seconds (conky update in frogs_lemonbar_conky
upd_vol=3                           # Volume update
upd_mail=15                         # Mail check update
upd_mpd=5                           # MPD song update

# color definitions 
color_back="#FF1D1F21"              # Default background
color_fore="#FFC5C8C6"              # Default foreground
#color_back="#FFC5C8C6"              # Light background
#color_fore="#FF1D1F21"              # Light foreground
color_head="#FF23CF25"              # Background for first element
color_sec_b1="#FF282A2E"            # Background for section 1
color_sec_b2="#FF454A4F"            # Background for section 2
color_sec_b3="#FF60676E"            # Background for section 3
color_icon="#FF979997"              # For icons
color_mail="#FFE51F32"              # Background color for mail alert
color_chat="#FFCC6666"              # Background color for chat alert
color_cpu="#FF5F819D"               # Background color for cpu alert
color_net="#FF4DFFBC"               # Background color for net alert
color_disable="#FF1D1F21"           # Foreground for disable elements
color_wsp="#FFC1C1C1"               # Background for selected workspace

color_batL="#FFFF481E"              # Background Color low Battery lvl
color_batM="#FFFF9B00"              # Background Color medium Battery lvl
color_batU="#FFCBD922"              # Background Color medium Battery lvl
color_batH="#FF71EE1B"              # Background Color high Battery lvl
color_batLoad="#FF9B35B7"           # Background Color loading Battery

#default space between sections
if [ ${res_w} -gt 1024 ]; then
  stab='  '
else
  stab=' '
fi

# Char glyps for powerline fonts
sep_left=""                        # Powerline separator left
sep_right=""                       # Powerline separator right
sep_l_left=""                      # Powerline light separator left
sep_l_right=""                     # Powerline light sepatator right

# Icon glyphs from Nerdfont
icon_clock=""                      # Clock icon
icon_cpu="﬙"                        # CPU icon
icon_mem=""                        # MEM icon
icon_dl=""                         # Download icon
icon_ul=""                         # Upload icon
icon_vol=""                        # Volume icon
icon_hd=""                         # HD / icon
icon_home="ﴤ"                       # HD /home icon
icon_mail=""                       # Mail icon
icon_chat=""                       # IRC/Chat icon
icon_music="ﱘ"                      # Music icon
icon_prog=""                       # Window icon
icon_contact=""                    # Contact icon
icon_wsp=""                        # Workspace icon
icon_os=""                         # os icon 
icon_wlan=""                       # wlan icon
icon_eth=""                        # net icon
icon_temp=""                       # temp icon
icon_battery=""                    # battery icon
icon_power=""                      # power plug icon
